run:
  tests: true

issues:
  max-same-issues: 0
  exclude-rules:
    - path: pkg/analyzer/analyzer_test.go
      text: 'compiler directive unrecognized: //go:debug'
      linters:
        - gocheckcompilerdirectives

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Antonboom/nilnil)

linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - forbidigo
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - nilnil
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
