# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: test

  tidy:
    cmds:
      - echo "Tidy..."
      - go mod tidy

  fmt:
    cmds:
      - echo "Fmt..."
      - golangci-lint fmt -v ./...

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run --fix ./...

  test:
    cmds:
      - echo "Tests..."
      - go test ./...

  test:coverage:
    cmds:
      - echo "Tests with coverage..."
      - go test -coverprofile=coverage.out ./...

  install:
    cmds:
      - echo "Install..."
      - go install ./...
